services:
  balancer:
    image: nginx:mainline-alpine3.21
    restart: unless-stopped
    labels:
      - dev.orbstack.domains=web.orb.local
    volumes:
      - ./web:/var/www/web
      - ./config/nginx:/etc/nginx/templates

  websocket:
    image: centrifugo/centrifugo:v6.1.0
    command: centrifugo -c config.json
    volumes:
      - ./config/centrifugo/config.json:/centrifugo/config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535