services:
  mysuperapp-1:
    build:
      context: .
      dockerfile: Dockerfile

  mysuperapp-2:
    build:
      context: .
      dockerfile: Dockerfile

  mysuperapp-3:
    build:
      context: .
      dockerfile: Dockerfile

  balancer:
    image: nginx:alpine3.21
    ports:
      - 8080:80
    volumes:
      - ./config/nginx:/etc/nginx/templates