version: "3"

dotenv:
  - .env

includes:
  migrate:
    dir: ./migrations
    taskfile: ./migrations/taskfile.yaml

tasks:
  up:
    cmd: docker compose up -d --build

  down:
    cmd: docker compose down

  restart:
    cmds:
      - task: down
      - task: up
