version: "3"

tasks:
  tidy:
    cmd: go mod tidy

  genproto:
    cmds:
      - protoc -I ./contracts proxy.proto --go_out=./internal/proxyproto --go-grpc_out=./internal/proxyproto
      - task: tidy

  gensql:
    cmds:
      - sqlc generate
      - task: tidy
