// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package demobase

type Account struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Enabled  bool   `json:"enabled"`
}

type Profile struct {
	ID         int64  `json:"id"`
	GivenName  string `json:"givenName"`
	FamilyName string `json:"familyName"`
	Email      string `json:"email"`
}
