// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profile.sql

package demobase

import (
	"context"
)

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, given_name, family_name, email FROM "public"."profile"
WHERE "id"=$1
`

func (q *Queries) GetProfileByID(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.GivenName,
		&i.FamilyName,
		&i.Email,
	)
	return i, err
}
